#!/bin/bash

code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension 1YiB.nodejs-bundle
code --install-extension 1YiB.svelte-bundle
code --install-extension ardenivanov.svelte-intellisense
code --install-extension bianxianyang.htmlplay
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension ecmel.vscode-html-css
code --install-extension fivethree.vscode-svelte-snippets
code --install-extension formulahendry.code-runner
code --install-extension formulahendry.code-runner-for-web
code --install-extension franneck94.c-cpp-runner
code --install-extension GitHub.copilot
code --install-extension golang.go
code --install-extension HarryHopkinson.vs-code-runner
code --install-extension jock.svg
code --install-extension Levertion.mcjson
code --install-extension mohd-akram.vscode-html-format
code --install-extension ms-dotnettools.csharp
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension oderwat.indent-rainbow
code --install-extension redhat.java
code --install-extension ritwickdey.LiveServer
code --install-extension rvest.vs-code-prettier-eslint
code --install-extension sgryjp.japanese-word-handler
code --install-extension sidthesloth.html5-boilerplate
code --install-extension standard.vscode-standard
code --install-extension svelte.svelte-vscode
code --install-extension tamasfe.even-better-toml
code --install-extension techer.open-in-browser
code --install-extension twxs.cmake
code --install-extension vadimcn.vscode-lldb
code --install-extension vscjava.vscode-gradle
code --install-extension wmanth.jar-viewer
code --install-extension yatki.vscode-surround
code --install-extension yodoware.vscode-reflow-japanese
code --install-extension Zignd.html-css-class-completion
